### ISSUE TITLE
横竖屏切换问题

### ISSUE THREAD

**Issue by FirstMorning** [yangchong211/YCVideoPlayer#101]
怎么禁止视频旋转  还有怎么禁止双击  暂停

**Comment by zfnian** [comment]
hi，请问您是怎么禁止横竖屏切换的？

**Comment by q88qaz** [comment]
controller = new BasisVideoController(mContext);
controller.setEnableOrientation(false);

**Comment by q88qaz** [comment]
BasisVideoController controller = new BasisVideoController(mContext);
controller.setEnableOrientation(false);

**Comment by q88qaz** [comment]
//创建基础视频播放器，一般播放器的功能
BasisVideoController controller = new BasisVideoController(mContext);
controller.setEnableOrientation(false);
//设置控制器
mVideoPlayer.setController(controller);
// 隐藏控制器
mVideoPlayer.setController(null);
