### ISSUE TITLE
建议作者开个QQ群，这是我见过文档写的最好的开源项目，呼吁大家赚钱了回报一下作者

### ISSUE THREAD

**Issue by ishangxue** [yangchong211/YCVideoPlayer#11]
如题，希望作者开个群，方便大家讨论。
很多封装写的都很好，但是没有这个文档全，所以老衲认为只要作者坚持住，此项目必火。
如果大家赚到了RMB，分点给作者吧。动力的源泉啊 O(∩_∩)O

**Comment by yangchong211** [comment]
好的，谢谢

在 2018-05-29 10:03:52，"ishangxue" <notifications@github.com> 写道：


如题，希望作者开个群，方便大家讨论。
很多封装写的都很好，但是没有这个文档全，所以老衲认为只要作者坚持住，此项目必火。
如果大家赚到了RMB，分点给作者吧。动力的源泉啊 O(∩_∩)O

**Comment by yangchong211** [comment]
好的，谢谢！

在 2018-05-29 10:13:21，"ishangxue" <notifications@github.com> 写道：


Closed #11.
