### ISSUE TITLE
播放过程中出现画面抖动问题作者这个问题遇见没

### ISSUE THREAD

**Issue by Greathfs** [yangchong211/YCVideoPlayer#2]

**Comment by yangchong211** [comment]
这个问题应该是视频的问题，视频在抖动。我之前遇见过，之前我是在七牛云存储上存放写视频，播放是没有问题的，但是由于七牛这边对流量有限制，所以有时候总是播放不了或者其他问题。于是我把视频源的视频链接改为jiaozi里的视频，就会有你说的这个视频抖动问题……

**Comment by Greathfs** [comment]
是这样的  我们播放的视频地址是优酷的m3u8地址  播放一段时间后 就会出现这个抖动问题 实在是不知道怎么弄比较好 使用原生的MediaPlayer 和谷歌Exoplayer 还有其他的播放器 有时候都会出现这个问题

**Comment by yangchong211** [comment]
好的，我会认真看一下这个问题。我也尝试使用优酷的m3u8地址播放视频，会逐渐修改bug的，多谢你的提示……

**Comment by Greathfs** [comment]
好的 我先把问题关了

**Comment by yangchong211** [comment]
你的问题目前解决了吗?
