### ISSUE TITLE
在哪个监听下获取视频长度比较好，能保证只获取一次

### ISSUE THREAD

**Issue by FLYANDHEIGHT** [yangchong211/YCVideoPlayer#20]

**Comment by FLYANDHEIGHT** [comment]
有些手机比如华为p10 7.0，vivo7.0表示视频播放器几分钟就显示播放失败

**Comment by yangchong211** [comment]
只要视频播放器初始化成功了，就可以获取到视频的长度，也就是总时间
long duration = mVideoPlayer.getDuration();
并且调用这个方法可以转化成HH：mm：ss
VideoPlayerUtils.formatTime(duration)
