### ISSUE TITLE
问一下这个新版的会员试看部分代码怎么没了

### ISSUE THREAD

**Issue by fancycy** [yangchong211/YCVideoPlayer#25]

**Comment by yangchong211** [comment]
被公司不懂技术的领导给说了，沟通无效之后，于是把那部分代码给删除了，还好没有承担责任。只有在本地才有的。其实添加该功能也不太复杂……

**Comment by yangchong211** [comment]
没办法，前公司强烈要求不能开源那部分代码的……不过播放器其正常播放的逻辑仍然没有改变……
