### ISSUE TITLE
播放音频seekTo()方法似乎无效

### ISSUE THREAD

**Issue by GzxdH** [yangchong211/YCVideoPlayer#36]
player.seekTo((duration / 1000) * position, MediaPlayer.SEEK_CLOSEST_SYNC);
player.start();

在这之前有调pause()方法。但是seekTo()方法似乎没有正确返回，debug运行，正常走到了start()方法。会出现MediaPlayer：Error（-2147483648，0）这样的错误。

请求帮助，谢谢。

**Comment by qiaoguoqiang** [comment]
设置了continueFromLastPosition的时候，seecTo会不起作用

**Comment by GzxdH** [comment]
> 设置了continueFromLastPosition的时候，seecTo会不起作用

感谢。
