### ISSUE TITLE
分享按钮点击事件没有使用listener

### ISSUE THREAD

**Issue by liduanwei** [yangchong211/YCVideoPlayer#38]
else if (v == mShare) {
            //分享
            Toast.makeText(mContext, "分享", Toast.LENGTH_SHORT).show();
            ///////////////////////////////
            mVideoControlListener.onVideoControlClick(ConstantKeys.VideoControl.SHARE);
            ///////////////////////////////
        } else if(v == mFlLock){
            //点击锁屏按钮，则进入锁屏模式
            setLock(mIsLock);
        } else if(v == mIvDownload){
            if(mVideoControlListener==null){
                VideoLogUtil.d("请在初始化的时候设置下载监听事件");
                return;
            }
            //点击下载
            mVideoControlListener.onVideoControlClick(ConstantKeys.VideoControl.DOWNLOAD);
        }

**Comment by yangchong211** [comment]
已经修改
