### ISSUE TITLE
支持下

### ISSUE THREAD

**Issue by CarGuo** [yangchong211/YCVideoPlayer#4]
嗯，这是我看过最长的readme，我居然看完了，哈哈哈，建议有时间把readme分一下为问题，更新历史，api，这样可能更舒服点(￣▽￣)／。

ijk的拖动后，seekbar跳动，可以通过` IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1`  解决部门视频问题，不过可能加长seek的缓冲时间。

切换视频清晰度有问题，是重新开始播放的问题，可以是你重新构建一个视频播放器，然后再播放器成功prepared，seek之后，在管理器中替换原本的player，把surface设置过去，这样有可以实现类似的无缝切换，其中的状态参数一并在构建时克隆过去，我基本是这么处理的。

期待你的后续更新。

**Comment by yangchong211** [comment]
嗯嗯，感谢大神的建议……
之前我也参考过你的代码，并且现在仍然在看。对于readme，的确有点长，是直接把写的博客文档复制过来的，后期参照你的那种格式，我再修改一下……
后期会持续更新的！
