### ISSUE TITLE
希望暴露模式切换时的监听

### ISSUE THREAD

**Issue by qiaoguoqiang** [yangchong211/YCVideoPlayer#43]
小窗口和全屏切换时可以监听到，加一些处理逻辑。

**Comment by yangchong211** [comment]
好的，这方面的逻辑已经添加上去了……
- 监听方法如下所示
    ```
    //视频播放模式监听
    controller.setOnPlayerTypeListener(new OnPlayerTypeListener() {
        /**
         * 切换到全屏播放监听
         */
        @Override
        public void onFullScreen() {
            LogUtils.e("setOnPlayerTypeListener"+"onFullScreen");
        }
        /**
         * 切换到小窗口播放监听
         */
        @Override
        public void onTinyWindow() {
            LogUtils.e("setOnPlayerTypeListener"+"onTinyWindow");
        }
        /**
         * 切换到正常播放监听
         */
        @Override
        public void onNormal() {
            LogUtils.e("setOnPlayerTypeListener"+"onNormal");
        }
    });
    ```
- 打印日志如下所示
```
2019-04-15 14:13:59.979 32151-32151/org.yczbj.ycvideoplayer E/VideoContentActivity: ║ main, onFullScreen(VideoContentActivity.java:290)
    ║ setOnPlayerTypeListeneronFullScreen
2019-04-15 14:14:02.978 32151-32151/org.yczbj.ycvideoplayer E/VideoContentActivity: ║ main, onNormal(VideoContentActivity.java:304)
    ║ setOnPlayerTypeListeneronNormal
2019-04-15 14:14:06.107 32151-32151/org.yczbj.ycvideoplayer E/VideoContentActivity: ║ main, onTinyWindow(VideoContentActivity.java:297)
    ║ setOnPlayerTypeListeneronTinyWindow
2019-04-15 14:14:08.264 32151-32151/org.yczbj.ycvideoplayer E/VideoContentActivity: ║ main, onNormal(VideoContentActivity.java:304)
    ║ setOnPlayerTypeListeneronNormal
```

**Comment by qiaoguoqiang** [comment]
> 好的，这方面的逻辑已经添加上去了……
> 
> * 监听方法如下所示
>   ```
>   //视频播放模式监听
>   controller.setOnPlayerTypeListener(new OnPlayerTypeListener() {
>       /**
>        * 切换到全屏播放监听
>        */
>       @Override
>       public void onFullScreen() {
>           LogUtils.e("setOnPlayerTypeListener"+"onFullScreen");
>       }
>       /**
>        * 切换到小窗口播放监听
>        */
>       @Override
>       public void onTinyWindow() {
>           LogUtils.e("setOnPlayerTypeListener"+"onTinyWindow");
>       }
>       /**
>        * 切换到正常播放监听
>        */
>       @Override
>       public void onNormal() {
>           LogUtils.e("setOnPlayerTypeListener"+"onNormal");
>       }
>   });
>   ```
> * 打印日志如下所示
> 
> ```
> 2019-04-15 14:13:59.979 32151-32151/org.yczbj.ycvideoplayer E/VideoContentActivity: ║ main, onFullScreen(VideoContentActivity.java:290)
>     ║ setOnPlayerTypeListeneronFullScreen
> 2019-04-15 14:14:02.978 32151-32151/org.yczbj.ycvideoplayer E/VideoContentActivity: ║ main, onNormal(VideoContentActivity.java:304)
>     ║ setOnPlayerTypeListeneronNormal
> 2019-04-15 14:14:06.107 32151-32151/org.yczbj.ycvideoplayer E/VideoContentActivity: ║ main, onTinyWindow(VideoContentActivity.java:297)
>     ║ setOnPlayerTypeListeneronTinyWindow
> 2019-04-15 14:14:08.264 32151-32151/org.yczbj.ycvideoplayer E/VideoContentActivity: ║ main, onNormal(VideoContentActivity.java:304)
>     ║ setOnPlayerTypeListeneronNormal
> ```

好的，谢谢，这个还是非常实用的
