### ISSUE TITLE
有两个问题最好优化一下

### ISSUE THREAD

**Issue by qiaoguoqiang** [yangchong211/YCVideoPlayer#44]
1、从全屏切换回普通模式，左上角返回不消失；
2、点击进入全屏后，右下角返回普通模式的按钮会消失，最好显示；

**Comment by qiaoguoqiang** [comment]
大佬，不想改你源码，想直接gradle引用，希望你能更新下，看你挺忙的，要不给个权限我帮你维护也行啊= =

**Comment by yangchong211** [comment]
第一个问题，左上角的返回键不管是普通播放模式，还是全屏播放模式，都是显示的，这个我参考了头条，优酷等视频播放器
第二个问题，关于右下角图表，采用你的建议，已经修改了……
如果你也想维护，可以直接pull代码上来……哈哈

**Comment by qiaoguoqiang** [comment]
但是从列表进入全屏，再返回列表，左上角显示返回按钮没啥意义呀

现在可以push了吗？我直接push提示没权限

**Comment by andych008** [comment]
> 但是从列表进入全屏，再返回列表，左上角显示返回按钮没啥意义呀
> 
> 现在可以push了吗？我之前push提示没权限

git协作的流程一般是：
1. 先clone别人的代码到自己的仓库（这样你就可以push了）；
2. 建一个分支，把你的修改commit并push到你的这个分支上（比如f01）；
3. 在github上new一个pull request请求大佬合入你的f01代码；
4. 大佬这时会收到github的通知，先review一下你的代码，如果觉得合格，就会merge进来，否则会打回，你继续改。

**Comment by yangchong211** [comment]
已经给你开通权限呢

在 2019-06-11 22:32:50，"喵叔catuncle" <notifications@github.com> 写道：


但是从列表进入全屏，再返回列表，左上角显示返回按钮没啥意义呀

现在可以push了吗？我之前push提示没权限

git协作的流程一般是：

先clone别人的代码到自己的仓库（这样你就可以push了）；
建一个分支，把你的修改commit并push到你的这个分支上（比如f01）；
在github上new一个pull request请求大佬合入你的f01代码；
大佬这时会收到github的通知，先review一下你的代码，如果觉得合格，就会merge进来，否则会打回，你继续改。

**Comment by andych008** [comment]
> 已经给你开通权限呢 在 2019-06-11 22:32:50，"喵叔catuncle" <notifications@github.com> 写道： 但是从列表进入全屏，再返回列表，左上角显示返回按钮没啥意义呀 现在可以push了吗？我之前push提示没权限 git协作的流程一般是： 先clone别人的代码到自己的仓库（这样你就可以push了）； 建一个分支，把你的修改commit并push到你的这个分支上（比如f01）； 在github上new一个pull request请求大佬合入你的f01代码； 大佬这时会收到github的通知，先review一下你的代码，如果觉得合格，就会merge进来，否则会打回，你继续改。 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

- 如果只开通了开发者权限developer(我在github没找到在哪里设置)，多数公司内部也是以这种方式。那么我可以在你的仓库里创建操作新分支，但往master分支或其它受保护分支也不能直接push，也得发pr，等你merge。
- 如果给我开通了master权限。那我几乎有和你同等的权限了，可以直接push commit到所有的分支。
