### ISSUE TITLE
enterVerticalScreenScreen比enterFullScreen流畅多了

### ISSUE THREAD

**Issue by qiaoguoqiang** [yangchong211/YCVideoPlayer#46]
感觉enterVerticalScreenScreen比enterFullScreen流畅多了，希望enterFullScreen优化一下，因为现在我用enterFullScreen会造成当前Activity闪退，原因找不出来，但是enterVerticalScreenScreen就不会。

**Comment by yangchong211** [comment]
- 解决办法
    - android:configChanges 保证了在全屏的时候横竖屏切换不会执行Activity的相关生命周期，打断视频的播放
    - android:screenOrientation 固定了屏幕的初始方向
    - 这两个变量控制全屏后和退出全屏的屏幕方向
    ```
        <activity android:name=".ui.VideoActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:screenOrientation="portrait"/>
    ```
- 为何不配置该属性会崩溃
    - 该配置作用是固定屏幕初始方向，如果不配置则会导致屏幕旋转重走activity的生命周期导致崩溃。
- 如果还不是这个问题，切换全屏导致崩溃，麻烦把日志上传一下，多谢！

**Comment by qiaoguoqiang** [comment]
这些我都加了，不是这个造成的，日志很少，几乎看不出啥，稍等我发一下

**Comment by qiaoguoqiang** [comment]
04-15 13:51:49.408 2982-2982/com.bandaorongmeiti.news D/YCVideoPlayer: onInfo ——> MEDIA_INFO_VIDEO_RENDERING_START：STATE_PLAYING
04-15 13:51:50.247 2982-2982/com.bandaorongmeiti.news I/YCVideoPlayer: 获取网络加载速度---------0
04-15 13:51:51.249 2982-2982/com.bandaorongmeiti.news I/YCVideoPlayer: 获取网络加载速度---------0
04-15 13:51:51.314 2982-2982/com.bandaorongmeiti.news I/YCVideoPlayer: 如果锁屏2，则屏蔽返回键
04-15 13:51:51.411 2982-2982/com.bandaorongmeiti.news I/YCVideoPlayer: 如果锁屏2，则屏蔽返回键
04-15 13:51:52.113 2982-3113/com.bandaorongmeiti.news D/EGL_adreno: eglMakeCurrent: 0xae977be0: ver 3 1 (tinfo 0xae839960)
04-15 13:51:52.116 2982-2982/com.bandaorongmeiti.news I/YCVideoPlayer: 注册电池监听广播
04-15 13:51:52.116 2982-2982/com.bandaorongmeiti.news D/YCVideoPlayer: MODE_FULL_SCREEN
04-15 13:51:52.157 2982-3113/com.bandaorongmeiti.news E/EGL_adreno: tid 3113: eglSurfaceAttrib(1266): error 0x3009 (EGL_BAD_MATCH)
04-15 13:51:52.157 2982-3113/com.bandaorongmeiti.news W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x9b446640, error=EGL_BAD_MATCH
04-15 13:51:52.160 2982-3113/com.bandaorongmeiti.news D/EGL_adreno: eglMakeCurrent: 0xae977be0: ver 3 1 (tinfo 0xae839960)
04-15 13:51:52.262 2982-2982/com.bandaorongmeiti.news D/YCVideoPlayer: STATE_PAUSED
04-15 13:51:52.291 2982-3113/com.bandaorongmeiti.news D/EGL_adreno: eglMakeCurrent: 0xae977be0: ver 3 1 (tinfo 0xae839960)
04-15 13:51:52.293 2982-2982/com.bandaorongmeiti.news D/YCVideoPlayer: MODE_NORMAL
04-15 13:51:52.363 2982-2982/com.bandaorongmeiti.news I/art: Explicit concurrent mark sweep GC freed 66834(2MB) AllocSpace objects, 17(3MB) LOS objects, 17% free, 74MB/90MB, paused 445us total 27.153ms
04-15 13:51:52.430 2982-2982/com.bandaorongmeiti.news I/YCVideoPlayer: 注册网络监听广播
04-15 13:51:52.433 2982-2982/com.bandaorongmeiti.news E/TAG: =======CurrentActivity========class com.bandao_new.activity.DetailVideoActivity
04-15 13:51:52.438 2982-2982/com.bandaorongmeiti.news D/YCVideoPlayer: onDetachedFromWindow
04-15 13:51:52.438 2982-2982/com.bandaorongmeiti.news I/YCVideoPlayer: 解绑注册网络监听广播
04-15 13:51:52.460 2982-2982/com.bandaorongmeiti.news I/art: Explicit concurrent mark sweep GC freed 13757(1115KB) AllocSpace objects, 3(2017KB) LOS objects, 17% free, 77MB/93MB, paused 334us total 21.645ms
04-15 13:51:52.469 2982-2982/com.bandaorongmeiti.news D/YCVideoPlayer: onAttachedToWindow
04-15 13:51:52.487 2982-3113/com.bandaorongmeiti.news E/EGL_adreno: tid 3113: eglSurfaceAttrib(1266): error 0x3009 (EGL_BAD_MATCH)
04-15 13:51:52.487 2982-3113/com.bandaorongmeiti.news W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x9b446640, error=EGL_BAD_MATCH
04-15 13:51:52.488 2982-3113/com.bandaorongmeiti.news D/EGL_adreno: eglMakeCurrent: 0xae977be0: ver 3 1 (tinfo 0xae839960)
04-15 13:51:52.511 2982-2982/com.bandaorongmeiti.news I/YCVideoPlayer: 获取网络加载速度---------0
04-15 13:51:52.511 2982-2982/com.bandaorongmeiti.news W/MediaPlayer: mediaplayer went away with unhandled events
04-15 13:51:52.512 2982-2982/com.bandaorongmeiti.news I/YCVideoPlayer: WIFI网络连上

**Comment by yangchong211** [comment]
没有看到你的异常崩溃日志……

**Comment by qiaoguoqiang** [comment]
是啊，控制台就输出这些，但是确实是没进入全屏闪退了，而且当前Activity重新加载了

**Comment by qiaoguoqiang** [comment]
我程序加了夜间模式，只有夜间模式会闪退，日间模式是好的，很奇怪
