### ISSUE TITLE
某些视频，Native播放正常，IJK播放会拉伸。

### ISSUE THREAD

**Issue by yuchf** [yangchong211/YCVideoPlayer#51]
播放地址：http://58.241.175.210:8081/cntv/media/new/2013/icntv2/media/newmedia/1.8M/2019/03/10/664283676.m3u8

Native播放：
![native](https://user-images.githubusercontent.com/4425671/56545533-74cdc980-65aa-11e9-9989-2bd732ca7fd6.jpg)
IJK播放：
![ijk](https://user-images.githubusercontent.com/4425671/56545535-74cdc980-65aa-11e9-84d3-0784a99354e4.jpg)

**Comment by yangchong211** [comment]
- 暂时没有复现这个问题，现在这版本添加了设置视频画面缩放模式，类似图片缩放那种。有6中
- 设置播放视频缩放类型。借鉴于网络博客，类似图片缩放。建议选择16：9类型，最常见
    ```
    mVideoPlayer.setScreenScaleType(ConstantKeys.PlayerScreenScaleType.SCREEN_SCALE_16_9);
    mVideoPlayer.setScreenScaleType(ConstantKeys.PlayerScreenScaleType.SCREEN_SCALE_DEFAULT);
    mVideoPlayer.setScreenScaleType(ConstantKeys.PlayerScreenScaleType.SCREEN_SCALE_4_3);
    mVideoPlayer.setScreenScaleType(ConstantKeys.PlayerScreenScaleType.SCREEN_SCALE_MATCH_PARENT);
    mVideoPlayer.setScreenScaleType(ConstantKeys.PlayerScreenScaleType.SCREEN_SCALE_ORIGINAL);
    mVideoPlayer.setScreenScaleType(ConstantKeys.PlayerScreenScaleType.SCREEN_SCALE_CENTER_CROP);
    ```
- 其实原理就是，在SurfaceView的测量方法中，根据设置缩放类型去改变视图的宽度和高度，来达到视频画面缩放。你可以再尝试一下
