### ISSUE TITLE
不支持https怎么破

### ISSUE THREAD

**Issue by GXSZone** [yangchong211/YCVideoPlayer#52]

**Comment by 748297973** [comment]
* int MEDIA_ERROR_IJK_PLAYER = -10000,//一般是视频源有问题或者数据格式不支持，比如音频不是AAC之类的

用别的试下就可以,我把https变成http可以播放但是没声音,说明视频源可以播放,https也应该可以的,如果是音频格式不支持,怎么破,或者说需要自己再怎么编译库吗

**Comment by zrg1215** [comment]
遇到相同问题，设置播放类型ConstantKeys.IjkPlayerType.TYPE_IJK， 重新设置成ConstantKeys.IjkPlayerType.TYPE_NATIVE就可以正常播放，有画面和声音

**Comment by 748297973** [comment]
> 遇到相同问题，设置播放类型ConstantKeys.IjkPlayerType.TYPE_IJK， 重新设置成ConstantKeys.IjkPlayerType.TYPE_NATIVE就可以正常播放，有画面和声音

我的是https的m3u8格式,我用饺子的库一起使用,目的是只打包饺子的so库让并没有使用饺子的代码,so库在让YCVideoPlayer加载,最后播放正常,看来是so库的问题编译应该没编译openssl,

**Comment by hxkdidi** [comment]
@748297973 我编译好了 可以播放https的视频了 ，但是ijk只支持h264编码的视频 ，只好改成TYPE_NATIVE。

**Comment by 748297973** [comment]
这个需要自己重新编译so库，具体搜索ijk的相关信息------------------ 原始邮件 ------------------
发件人: "hxkdyw"<notifications@github.com>
发送时间: 2019年5月10日(星期五) 上午10:01
收件人: "yangchong211/YCVideoPlayer"<YCVideoPlayer@noreply.github.com>;
抄送: "748297973"<2228534959@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [yangchong211/YCVideoPlayer] 不支持https怎么破 (#52)



@748297973 我编译好了 可以播放https的视频了 ，但是ijk只支持h264编码的视频 ，只好改成TYPE_NATIVE。
 
&mdash;

**Comment by wentaojava** [comment]
这是来自QQ邮箱的假期自动回复邮件。Hello, I'm busy now, unable to reply you timely
