### ISSUE TITLE
多次切换正常模式和横屏模式，回到正常模式视频画面不完整

### ISSUE THREAD

**Issue by hxkdidi** [yangchong211/YCVideoPlayer#53]

**Comment by hxkdidi** [comment]
fragment的recycleView列表中，使用的TYPE_NATIVE模式播放，有时候第一次从正常模式切换到横屏模式也会出现。

**Comment by hxkdidi** [comment]
是给视频TextureView设置了圆角，注释就好了
 //if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
//                    mTextureView.setOutlineProvider(new TextureVideoViewOutlineProvider(DisplayUtils.dp2px(getContext(),5)));
//                    mTextureView.setClipToOutline(true);
//                }

**Comment by yangchong211** [comment]
非常感谢，最近的确有点忙，谢谢你的建议……
