### ISSUE TITLE
电影模块加载不了。

### ISSUE THREAD

**Issue by wzy888** [yangchong211/YCVideoPlayer#56]
电影模块转圈，加载不了。错误日志：
E/OkHttp: log = <-- 403 Forbidden http://api.svipmovie.com/front/homePageApi/homePage.do (84ms)   后台接口有点问题，新闻界面一个解析时间，使用的第三方TimeUtils.getFriendlyTimeSpanByNow(tv_datetime) ，有点小毛病。

**Comment by yangchong211** [comment]
已经去掉了那个模块呢
