### ISSUE TITLE
jiaozivideoplayer 和YCVideoPlayerLib 都是视频库吗，怎么不合并到一起呢？

### ISSUE THREAD

**Issue by tianshaokai** [yangchong211/YCVideoPlayer#6]

**Comment by yangchong211** [comment]
是借鉴jiaozi播放器的思路。然后另外一个YCVideoPlayerLib是自己慢慢写的……两个都是视频封装库，如果需要集成，可以添加compile 'cn.yc:YCVideoPlayerLib:2.3'即可。后期持续更新！
