### ISSUE TITLE
视频播放 有些加载很快点击就秒放，有些又很慢

### ISSUE THREAD

**Issue by zhoulongwu11** [yangchong211/YCVideoPlayer#62]
http://dfjszx.com/1568788266922.mp4，慢连接
http://vfx.mtime.cn/Video/2019/02/04/mp4/190204084208765161.mp4，快连接

**Comment by yangchong211** [comment]
这个是视频解码的问题，你把这两个视频链接放到浏览器中播放也会出现你说的问题。跟视频源有关系……
具体可以设置videoPlayer.setPlayerType(ConstantKeys.IjkPlayerType.TYPE_IJK);支持ijk解码，支持绝大多数的播放视频，关于一些参数设置，可以看一下下面代码
        //设置ijkPlayer播放器的硬件解码相关参数
        //设置播放前的最大探测时间
        ((IjkMediaPlayer)mMediaPlayer).setOption(format, "analyzemaxduration", 100L);
        //设置播放前的探测时间 1,达到首屏秒开效果
        ((IjkMediaPlayer)mMediaPlayer).setOption(format, "analyzeduration", 1L);
        //播放前的探测Size，默认是1M, 改小一点会出画面更快
        ((IjkMediaPlayer)mMediaPlayer).setOption(format, "probesize", 10240L);
        //设置是否开启变调isModifyTone?0:1
        ((IjkMediaPlayer)mMediaPlayer).setOption(player,"soundtouch",0);
        //每处理一个packet之后刷新io上下文
        ((IjkMediaPlayer)mMediaPlayer).setOption(format, "flush_packets", 1L);
        //是否开启预缓冲，一般直播项目会开启，达到秒开的效果，不过带来了播放丢帧卡顿的体验
        ((IjkMediaPlayer)mMediaPlayer).setOption(player, "packet-buffering", 0L);
        //播放重连次数
        ((IjkMediaPlayer)mMediaPlayer).setOption(player, "reconnect", 5);
        //最大缓冲大小,单位kb
        ((IjkMediaPlayer)mMediaPlayer).setOption(player, "max-buffer-size", 10240L);
        //跳帧处理,放CPU处理较慢时，进行跳帧处理，保证播放流程，画面和声音同步
        ((IjkMediaPlayer)mMediaPlayer).setOption(player, "framedrop", 1L);
        //最大fps
        ((IjkMediaPlayer)mMediaPlayer).setOption(player, "max-fps", 30L);
        //SeekTo设置优化
        ((IjkMediaPlayer)mMediaPlayer).setOption(player, "enable-accurate-seek", 1L);
        ((IjkMediaPlayer)mMediaPlayer).setOption(player, "opensles", 0);
        ((IjkMediaPlayer)mMediaPlayer).setOption(player, "overlay-format",
                IjkMediaPlayer.SDL_FCC_RV32);
        ((IjkMediaPlayer)mMediaPlayer).setOption(player, "framedrop", 1);
        ((IjkMediaPlayer)mMediaPlayer).setOption(player, "start-on-prepared", 0);
        ((IjkMediaPlayer)mMediaPlayer).setOption(format, "http-detect-range-support", 0);
        //设置是否开启环路过滤: 0开启，画面质量高，解码开销大，48关闭，画面质量差点，解码开销小
        ((IjkMediaPlayer)mMediaPlayer).setOption(codec, "skip_loop_filter", 48);

        //jkPlayer支持硬解码和软解码。
        //软解码时不会旋转视频角度这时需要你通过onInfo的what == IMediaPlayer.MEDIA_INFO_VIDEO_ROTATION_CHANGED去获取角度，自己旋转画面。
        //或者开启硬解硬解码，不过硬解码容易造成黑屏无声（硬件兼容问题），下面是设置硬解码相关的代码
        ((IjkMediaPlayer)mMediaPlayer).setOption(player, "mediacodec", 0);
        ((IjkMediaPlayer)mMediaPlayer).setOption(player, "mediacodec-auto-rotate", 1);
        ((IjkMediaPlayer)mMediaPlayer).setOption(player, "mediacodec-handle-resolution-change", 1);
