### ISSUE TITLE
为什么不能 设置完参数 就videoPlayer.start();  硬要用户自己去点开始button播放；很不人性啊！

### ISSUE THREAD

**Issue by androidforme** [yangchong211/YCVideoPlayer#63]

**Comment by androidforme** [comment]
我要进入activity 就自动播放 如何操作videoPlayer.start();

**Comment by yangchong211** [comment]
你可以调用start()方法播放视频。逻辑没有问题……注意需要延迟操作，避免没有初始化玩调用start()方法
        videoPlayer.postDelayed(new Runnable() {
            @Override
            public void run() {
                videoPlayer.start();
            }
        },500);
