### ISSUE TITLE
列表滑动卡顿

### ISSUE THREAD

**Issue by wangjingbo520** [yangchong211/YCVideoPlayer#84]
用listview或者recyclerview滑动列表，很明显的卡顿

**Comment by 15234255240** [comment]
是因为代码中设置了播放器不显示在可见区域就会gc回收，造成了ui线程卡顿，我找了好久才发现这个问题

**Comment by yangchong211** [comment]
嗯，已经修改了这个问题。在新的播放器中，list条目列表中，只创建一个VideoPlayer，那个播放就添加到具体的item布局中。比如播放第一个视频就把player对象添加到视图中，点击播放第三个时需要把player从它的父布局中移除后然后再添加到该item的布局中。
并且添加了列表预加载的功能，完美解决了这个问题
