### ISSUE TITLE
空指针

### ISSUE THREAD

**Issue by StartSunday** [yangchong211/YCVideoPlayer#90]
工具 as 4.1  gradle 6.5  华化8.1手机
![image](https://user-images.githubusercontent.com/26109908/98193785-ef75f400-1f58-11eb-8828-eaaba03fcd0a.png)
![image](https://user-images.githubusercontent.com/26109908/98193794-f7359880-1f58-11eb-9dee-45bf787eb976.png)
指向位置
![image](https://user-images.githubusercontent.com/26109908/98193827-03215a80-1f59-11eb-98f2-926abf9a892b.png)

**Comment by StartSunday** [comment]
华为手机

**Comment by yangchong211** [comment]
之前代码
    public CustomErrorView(Context context) {
        this(context, null);
        init(context);
    }
之后代码
    public CustomErrorView(Context context) {
        super(context);
        init(context);
    }
已经修改

**Comment by yangchong211** [comment]
你看拉一下代码，已经解决了
